### ISSUE TITLE
Polygon errors on board maker website

### ISSUE THREAD

**Issue by alex-x-taylor** [NPoole/KeychainTapeCounter#6]
I attempted to upload the .brd files to get some boards made (oshpark) and got an error code. After reaching out to support and submitting a file to them they say that there are some polygons with mismatch ends. An example they gave was instead of a corner coming to a nice 90 degree point, it overlaps and turns into a small bow tie. I'm planning on combing through the board designs and looking for any wayward polygons.

Thanks for your hard work!

**Comment by NPoole** [comment]
Yeah, I'm aware of these errors because both Eagle and the CAM script that I use to generate the gerber files complain about them. They're the result of images that were generated from SVGs using another tool that I created called "Vulture" which still has bugs in it. If you manage to manually correct the polygons, please submit a pull request and I'll pull the corrected polygons so future DIYers don't have to deal with them. Thanks!
